"use client";

import Link from "next/link";
import { AlertTriangle, ArrowRight, BookOpen, Landmark, ShieldCheck } from "lucide-react";
import { Language, useLanguage } from "@/context/LanguageContext";

type Copy = { eyebrow: string; title: string; intro: string; ask: string; safety: string; caution: string; learn: string; disclaimer: string; topics: [string, string][] };
const topics = {
  en: [["Understanding Loans", "A loan, repayment schedule and the questions to ask a lender."], ["Interest & EMI", "Simple and compound interest, and how an EMI works."], ["Cooperative Credit & KCC", "General guidance on cooperative credit and Kisan Credit Card."], ["Savings & Crop Insurance", "Savings basics and why policy terms matter for insurance."], ["Digital Payment Safety", "How to spot common fraud attempts and protect credentials."], ["Credit & Documents", "Credit-score basics and keeping financial records secure."]],
  hi: [["ऋण को समझें", "ऋण, पुनर्भुगतान कार्यक्रम और ऋणदाता से पूछे जाने वाले प्रश्न।"], ["ब्याज और EMI", "सरल व चक्रवृद्धि ब्याज तथा EMI कैसे काम करती है।"], ["सहकारी ऋण और KCC", "सहकारी ऋण और किसान क्रेडिट कार्ड पर सामान्य मार्गदर्शन।"], ["बचत और फसल बीमा", "बचत की मूल बातें और बीमा में पॉलिसी शर्तों का महत्व।"], ["डिजिटल भुगतान सुरक्षा", "आम धोखाधड़ी प्रयासों को पहचानें और अपने प्रमाण-पत्र सुरक्षित रखें।"], ["क्रेडिट और दस्तावेज़", "क्रेडिट स्कोर की मूल बातें और वित्तीय रिकॉर्ड सुरक्षित रखना।"]],
  kn: [["ಸಾಲಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ", "ಸಾಲ, ಮರುಪಾವತಿ ವೇಳಾಪಟ್ಟಿ ಮತ್ತು ಸಾಲದಾತರಿಗೆ ಕೇಳಬೇಕಾದ ಪ್ರಶ್ನೆಗಳು."], ["ಬಡ್ಡಿ ಮತ್ತು EMI", "ಸರಳ, ಚಕ್ರಬಡ್ಡಿ ಮತ್ತು EMI ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ."], ["ಸಹಕಾರಿ ಸಾಲ ಮತ್ತು KCC", "ಸಹಕಾರಿ ಸಾಲ ಮತ್ತು ಕಿಸಾನ್ ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್ ಕುರಿತ ಸಾಮಾನ್ಯ ಮಾರ್ಗದರ್ಶನ."], ["ಉಳಿತಾಯ ಮತ್ತು ಬೆಳೆ ವಿಮೆ", "ಉಳಿತಾಯದ ಮೂಲಭೂತಗಳು ಮತ್ತು ವಿಮೆಯ ಪಾಲಿಸಿ ನಿಯಮಗಳ ಮಹತ್ವ."], ["ಡಿಜಿಟಲ್ ಪಾವತಿ ಸುರಕ್ಷತೆ", "ಸಾಮಾನ್ಯ ವಂಚನೆ ಪ್ರಯತ್ನಗಳನ್ನು ಗುರುತಿಸಿ ಮತ್ತು ಪ್ರಮಾಣಪತ್ರಗಳನ್ನು ರಕ್ಷಿಸಿ."], ["ಕ್ರೆಡಿಟ್ ಮತ್ತು ದಾಖಲೆಗಳು", "ಕ್ರೆಡಿಟ್ ಸ್ಕೋರ್‌ನ ಮೂಲಭೂತಗಳು ಮತ್ತು ಹಣಕಾಸು ದಾಖಲೆಗಳ ಸುರಕ್ಷತೆ."]],
  mr: [["कर्ज समजून घ्या", "कर्ज, परतफेड वेळापत्रक आणि कर्जदात्याला विचारायचे प्रश्न."], ["व्याज आणि EMI", "साधे व चक्रवाढ व्याज आणि EMI कशी काम करते."], ["सहकारी पत आणि KCC", "सहकारी पत व किसान क्रेडिट कार्डबाबत सामान्य मार्गदर्शन."], ["बचत आणि पीक विमा", "बचतीची मूलतत्त्वे आणि विम्यातील पॉलिसी अटींचे महत्त्व."], ["डिजिटल पेमेंट सुरक्षा", "सामान्य फसवणुकीचे प्रयत्न ओळखा आणि प्रमाणपत्रे सुरक्षित ठेवा."], ["पत आणि दस्तऐवज", "क्रेडिट स्कोअरची मूलतत्त्वे आणि आर्थिक नोंदी सुरक्षित ठेवणे."]],
  te: [["రుణాలను అర్థం చేసుకోండి", "రుణం, తిరిగి చెల్లింపు షెడ్యూల్ మరియు రుణదాతను అడగవలసిన ప్రశ్నలు."], ["వడ్డీ మరియు EMI", "సాధారణ, చక్రవడ్డీ మరియు EMI ఎలా పనిచేస్తాయో తెలుసుకోండి."], ["సహకార రుణం మరియు KCC", "సహకార రుణం మరియు కిసాన్ క్రెడిట్ కార్డ్‌పై సాధారణ మార్గదర్శకం."], ["పొదుపు మరియు పంట బీమా", "పొదుపు ప్రాథమికాలు మరియు బీమా పాలసీ నిబంధనల ప్రాముఖ్యత."], ["డిజిటల్ చెల్లింపు భద్రత", "సాధారణ మోస ప్రయత్నాలను గుర్తించి ఆధారాలను రక్షించండి."], ["క్రెడిట్ మరియు పత్రాలు", "క్రెడిట్ స్కోర్ ప్రాథమికాలు మరియు ఆర్థిక రికార్డుల భద్రత."]],
} as Record<Language, [string, string][]>;
const copy: Record<Language, Omit<Copy, "topics">> = {
  en: { eyebrow: "Educational guidance", title: "Financial Literacy", intro: "Clear, general education for cooperative members and farmers — never banking or investment advice.", ask: "Ask Mitra about financial literacy", safety: "Important safety notice.", caution: "Never share an OTP, PIN, password, card number, or bank-login details.", learn: "Learn with Mitra", disclaimer: "This information is for general financial education and does not constitute personalized financial, investment, banking or legal advice. Consult the relevant regulated or authorized institution or a qualified professional for specific decisions." },
  hi: { eyebrow: "शैक्षिक मार्गदर्शन", title: "वित्तीय साक्षरता", intro: "सहकारी सदस्यों और किसानों के लिए स्पष्ट सामान्य शिक्षा — बैंकिंग या निवेश संबंधी सलाह नहीं।", ask: "वित्तीय साक्षरता के बारे में मित्र से पूछें", safety: "महत्वपूर्ण सुरक्षा सूचना।", caution: "OTP, PIN, पासवर्ड, कार्ड नंबर या बैंक-लॉगिन विवरण कभी साझा न करें।", learn: "मित्र के साथ सीखें", disclaimer: "यह जानकारी सामान्य वित्तीय शिक्षा के लिए है और व्यक्तिगत वित्तीय, निवेश, बैंकिंग या कानूनी सलाह नहीं है। विशेष निर्णयों के लिए संबंधित विनियमित या अधिकृत संस्था अथवा योग्य विशेषज्ञ से परामर्श करें।" },
  kn: { eyebrow: "ಶೈಕ್ಷಣಿಕ ಮಾರ್ಗದರ್ಶನ", title: "ಹಣಕಾಸು ಸಾಕ್ಷರತೆ", intro: "ಸಹಕಾರಿ ಸದಸ್ಯರು ಮತ್ತು ರೈತರಿಗೆ ಸ್ಪಷ್ಟ ಸಾಮಾನ್ಯ ಶಿಕ್ಷಣ — ಬ್ಯಾಂಕಿಂಗ್ ಅಥವಾ ಹೂಡಿಕೆ ಸಲಹೆಯಲ್ಲ.", ask: "ಹಣಕಾಸು ಸಾಕ್ಷರತೆ ಬಗ್ಗೆ ಮಿತ್ರರನ್ನು ಕೇಳಿ", safety: "ಪ್ರಮುಖ ಸುರಕ್ಷತಾ ಸೂಚನೆ.", caution: "OTP, PIN, ಪಾಸ್‌ವರ್ಡ್, ಕಾರ್ಡ್ ಸಂಖ್ಯೆ ಅಥವಾ ಬ್ಯಾಂಕ್-ಲಾಗಿನ್ ವಿವರಗಳನ್ನು ಎಂದಿಗೂ ಹಂಚಿಕೊಳ್ಳಬೇಡಿ.", learn: "ಮಿತ್ರರೊಂದಿಗೆ ಕಲಿಯಿರಿ", disclaimer: "ಈ ಮಾಹಿತಿಯು ಸಾಮಾನ್ಯ ಹಣಕಾಸು ಶಿಕ್ಷಣಕ್ಕಾಗಿ ಮಾತ್ರ; ಇದು ವೈಯಕ್ತಿಕ ಹಣಕಾಸು, ಹೂಡಿಕೆ, ಬ್ಯಾಂಕಿಂಗ್ ಅಥವಾ ಕಾನೂನು ಸಲಹೆಯಲ್ಲ. ನಿರ್ದಿಷ್ಟ ನಿರ್ಧಾರಗಳಿಗೆ ಸಂಬಂಧಿತ ನಿಯಂತ್ರಿತ ಅಥವಾ ಅಧಿಕೃತ ಸಂಸ್ಥೆ ಅಥವಾ ಅರ್ಹ ವೃತ್ತಿಪರರನ್ನು ಸಂಪರ್ಕಿಸಿ." },
  mr: { eyebrow: "शैक्षणिक मार्गदर्शन", title: "आर्थिक साक्षरता", intro: "सहकारी सदस्य आणि शेतकऱ्यांसाठी स्पष्ट सामान्य शिक्षण — बँकिंग किंवा गुंतवणूक सल्ला नाही.", ask: "आर्थिक साक्षरतेबद्दल मित्राला विचारा", safety: "महत्त्वाची सुरक्षा सूचना.", caution: "OTP, PIN, पासवर्ड, कार्ड क्रमांक किंवा बँक-लॉगिन तपशील कधीही शेअर करू नका.", learn: "मित्रासोबत शिका", disclaimer: "ही माहिती सामान्य आर्थिक शिक्षणासाठी आहे; ती वैयक्तिक आर्थिक, गुंतवणूक, बँकिंग किंवा कायदेशीर सल्ला नाही. विशिष्ट निर्णयांसाठी संबंधित नियमनबद्ध किंवा अधिकृत संस्था अथवा पात्र व्यावसायिकांचा सल्ला घ्या." },
  te: { eyebrow: "విద్యా మార్గదర్శకం", title: "ఆర్థిక అవగాహన", intro: "సహకార సభ్యులు మరియు రైతులకు స్పష్టమైన సాధారణ విద్య — బ్యాంకింగ్ లేదా పెట్టుబడి సలహా కాదు.", ask: "ఆర్థిక అవగాహన గురించి మిత్రను అడగండి", safety: "ముఖ్యమైన భద్రతా సూచన.", caution: "OTP, PIN, పాస్‌వర్డ్, కార్డ్ నంబర్ లేదా బ్యాంక్-లాగిన్ వివరాలను ఎప్పుడూ పంచుకోవద్దు.", learn: "మిత్రతో నేర్చుకోండి", disclaimer: "ఈ సమాచారం సాధారణ ఆర్థిక విద్య కోసం మాత్రమే; ఇది వ్యక్తిగత ఆర్థిక, పెట్టుబడి, బ్యాంకింగ్ లేదా న్యాయ సలహా కాదు. నిర్దిష్ట నిర్ణయాల కోసం సంబంధిత నియంత్రిత లేదా అధీకృత సంస్థను లేదా అర్హత కలిగిన నిపుణుడిని సంప్రదించండి." },
};

export default function FinancialLiteracyPage() {
  const { language } = useLanguage(); const t: Copy = { ...copy[language], topics: topics[language] };
  return <div className="min-h-screen bg-[#f5f7f4] text-slate-900"><section className="bg-[#173b2a] py-14 text-white"><div className="container-public px-5"><div className="flex items-center gap-2 text-sm font-semibold text-[#dcae2f]"><Landmark className="h-5 w-5" /> {t.eyebrow}</div><h1 className="mt-4 text-4xl font-semibold">{t.title}</h1><p className="mt-4 max-w-2xl text-[#d6e4da]">{t.intro}</p><Link href="/chat" className="mt-7 inline-flex items-center gap-2 bg-[#16824c] px-5 py-3 text-sm font-bold">{t.ask} <ArrowRight className="h-4 w-4" /></Link></div></section><section className="container-public px-5 py-10"><div className="mb-8 flex gap-3 border-l-4 border-amber-500 bg-amber-50 p-4 text-sm leading-6 text-amber-950" role="note" aria-label={t.safety}><AlertTriangle className="h-5 w-5 shrink-0 text-amber-700" aria-hidden="true" /><div><strong>{t.safety}</strong> {t.caution}</div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{t.topics.map(([title, description]) => <article key={title} className="border border-slate-200 bg-white p-5 shadow-sm"><BookOpen className="h-5 w-5 text-[#16824c]" /><h2 className="mt-3 font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p><Link href={`/chat?question=${encodeURIComponent(title)}`} className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-[#16824c]">{t.learn} <ArrowRight className="h-4 w-4" /></Link></article>)}</div><div className="mt-8 flex gap-3 border border-[#b9e7ca] bg-[#f0faf4] p-5 text-sm text-slate-700"><ShieldCheck className="h-5 w-5 shrink-0 text-[#16824c]" /><p>{t.disclaimer}</p></div></section></div>;
}
