"""initial_tables

Revision ID: 3d39631a2649
Revises: 
Create Date: 2026-09-18 11:27:15.981380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d39631a2649'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_acts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('act_code', sa.String(length=50), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('title_hi', sa.String(length=255), nullable=False),
    sa.Column('title_kn', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=False),
    sa.Column('enacted_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('official_source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_acts_act_code'), 'legal_acts', ['act_code'], unique=True)
    op.create_index(op.f('ix_legal_acts_id'), 'legal_acts', ['id'], unique=False)
    op.create_table('schemes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('title_hi', sa.String(length=255), nullable=False),
    sa.Column('title_kn', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('ministry_or_agency', sa.String(length=255), nullable=False),
    sa.Column('target_beneficiaries', sa.JSON(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_hi', sa.Text(), nullable=False),
    sa.Column('description_kn', sa.Text(), nullable=False),
    sa.Column('eligibility_criteria', sa.JSON(), nullable=False),
    sa.Column('benefits_summary', sa.Text(), nullable=False),
    sa.Column('application_process', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_citation', sa.String(length=255), nullable=False),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schemes_category'), 'schemes', ['category'], unique=False)
    op.create_index(op.f('ix_schemes_code'), 'schemes', ['code'], unique=True)
    op.create_index(op.f('ix_schemes_id'), 'schemes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('pacs_name', sa.String(length=255), nullable=True),
    sa.Column('pacs_registration_number', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_uuid', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_session_uuid'), 'chat_sessions', ['session_uuid'], unique=True)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('grievances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('pacs_name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievances_id'), 'grievances', ['id'], unique=False)
    op.create_index(op.f('ix_grievances_status'), 'grievances', ['status'], unique=False)
    op.create_index(op.f('ix_grievances_ticket_number'), 'grievances', ['ticket_number'], unique=True)
    op.create_index(op.f('ix_grievances_user_id'), 'grievances', ['user_id'], unique=False)
    op.create_table('legal_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=False),
    sa.Column('chapter', sa.String(length=100), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('title_hi', sa.String(length=255), nullable=False),
    sa.Column('title_kn', sa.String(length=255), nullable=False),
    sa.Column('simplified_en', sa.Text(), nullable=False),
    sa.Column('simplified_hi', sa.Text(), nullable=False),
    sa.Column('simplified_kn', sa.Text(), nullable=False),
    sa.Column('official_text', sa.Text(), nullable=False),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.Column('source_citation', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['legal_acts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_sections_act_id'), 'legal_sections', ['act_id'], unique=False)
    op.create_index(op.f('ix_legal_sections_id'), 'legal_sections', ['id'], unique=False)
    op.create_index(op.f('ix_legal_sections_section_number'), 'legal_sections', ['section_number'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('provider_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_legal_sections_section_number'), table_name='legal_sections')
    op.drop_index(op.f('ix_legal_sections_id'), table_name='legal_sections')
    op.drop_index(op.f('ix_legal_sections_act_id'), table_name='legal_sections')
    op.drop_table('legal_sections')
    op.drop_index(op.f('ix_grievances_user_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_ticket_number'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_status'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_id'), table_name='grievances')
    op.drop_table('grievances')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_session_uuid'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schemes_id'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_code'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_category'), table_name='schemes')
    op.drop_table('schemes')
    op.drop_index(op.f('ix_legal_acts_id'), table_name='legal_acts')
    op.drop_index(op.f('ix_legal_acts_act_code'), table_name='legal_acts')
    op.drop_table('legal_acts')
    # ### end Alembic commands ###
